# Generated by Django 2.2 on 2019-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
